runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GCP_PROJECT_ID: $GCP_PROJECT_ID
  GCP_BUCKET_NAME: $GCP_BUCKET_NAME
  OPENAI_API_KEY: $OPENAI_API_KEY

handlers:
- url: /.*
  script: auto

instance_class: F2
