runtime: python38
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_CLOUD_PROJECT: your-project-id

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

instance_class: F2